AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Description: Select Dev, QA, Prod environment.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Resources:
  BookSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref Environment, "books"]]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BooksApp

  BookS3BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref Environment, "gruzjeka-books"]]
      AccessControl: Private
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BooksApp

  BookDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "ISBN"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ISBN"
          KeyType: "HASH"
      TableName: !Join ["-", [!Ref Environment, "books"]]
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref Environment

  BookSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow ssh and http:80"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

  BookDeploymentS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref Environment, "gruzjeka-books-artifacts"]]
      AccessControl: Private
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BooksApp

  BookVMExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allowS3Read
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - arn:aws:s3:::aws-codedeploy-us-east-1/*
                  - !GetAtt BookDeploymentS3Bucket.Arn

  ListS3BucketsInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref BookVMExecutionRole

  BookVM:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-01fbc92d24852df9b
      InstanceType: t2.micro
      KeyName: gruzjeka_key
      SecurityGroupIds: [!Ref BookSecurityGroup]
      IamInstanceProfile: !Ref ListS3BucketsInstanceProfile
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash -x
          yum -y update
          yum install -y ruby
          cd /home/ec2-user
          curl -O https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BooksApp

  BooksSQSToS3BackupFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allowLambdaLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: allowSqs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt BookSQSQueue.Arn
        - PolicyName: allowBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject*
                  - s3:GetBucket*
                  - s3:List*
                  - s3:DeleteObject*
                  - s3:PutObject*
                  - s3:Abort*
                Resource: !Join ["", [!GetAtt BookS3BackupBucket.Arn, "/*"]]

  BooksSQSToS3BackupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BooksSQSToS3BackupFunction
      CodeUri: "s3://gruzjeka-books-defaults/default-lambda.zip"
      Handler: S3Backup::S3Backup.SqsToS3BackupFunction::FunctionHandler
      Runtime: dotnetcore2.1
      Role: !GetAtt BooksSQSToS3BackupFunctionExecutionRole.Arn
      Timeout: 30
      Environment:
        Variables:
          BackupS3BucketName: !Ref BookS3BackupBucket
          Region: !Ref "AWS::Region"

  BooksSQSToS3BackupFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt BookSQSQueue.Arn
      FunctionName: !GetAtt BooksSQSToS3BackupFunction.Arn

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess

  BookLambdaDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: lambda-books
      ComputePlatform: Lambda

  BookLambdaDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref BookLambdaDeployApplication
      DeploymentGroupName: !Ref Environment
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
      DeploymentStyle:
        DeploymentOption: WITH_TRAFFIC_CONTROL
        DeploymentType: BLUE_GREEN

  BookEC2DeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: ec2-books
      ComputePlatform: Server

  BookVMDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref BookEC2DeployApplication
      DeploymentGroupName: !Ref Environment
      Ec2TagFilters:
        - Key: Environment
          Value: !Ref Environment
          Type: "KEY_AND_VALUE"
        - Key: Application
          Value: BooksApp
          Type: "KEY_AND_VALUE"
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
