AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Description: Select Dev, QA, Prod environment.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Resources:
  BookSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref "Environment", "books"]]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BooksApp

  BookS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref "Environment", "gruzjeka-books"]]
      AccessControl: Private
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BooksApp

  BookDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "ISBN"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ISBN"
          KeyType: "HASH"
      TableName: !Join ["-", [!Ref "Environment", "books"]]
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref Environment

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allowLambdaLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: allowSqs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt BookSQSQueue.Arn
        - PolicyName: allowBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !GetAtt BookS3Bucket.Arn

  BookLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "s3://gruzjeka-test-bucket/publish.zip"
      Handler: MyFunction.FunctionHandler
      Runtime: dotnetcore2.1
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BookSQSQueue.Arn
            BatchSize: 10

  BookSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow ssh and http:80"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

  BookVM:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-07ebfd5b3428b6f4d
      InstanceType: t2.micro
      KeyName: gruzjeka_key
      SecurityGroupIds: [!Ref BookSecurityGroup]
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash -x
          echo 'hello world'
